export const previewBranch = (pr) => `preview/pr${pr}-staging`;
export const previewUrl = (pr) => `https://magpie-pr${pr}.staged.apache.org/`;

/**
 * Generated by the publisher, never taken from the artifact: an .asf.yaml
 * shipped by a pull request could name a different profile or a publish block.
 */
export function renderAsfYaml(pr) {
  return `# Generated by preview-publish. Do not edit.
# Serves this branch at ${previewUrl(pr)}
staging:
  profile: pr${pr}
  whoami: ${previewBranch(pr)}
`;
}

export function renderRobots() {
  return `User-agent: *
Disallow: /
`;
}

/**
 * Deleting a branch does not unstage the site, so a retired preview is
 * overwritten with this before its branch is deleted.
 */
export function renderTombstone({ pr, repo }) {
  const url = `https://github.com/${repo}/pull/${pr}`;
  return `<!doctype html>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<title>Preview retired — PR #${pr}</title>
<h1>This preview has been retired</h1>
<p>The preview for pull request #${pr} is no longer published, because the
pull request is closed or is no longer armed for previews.</p>
<p><a href="${url}">${url}</a></p>
`;
}
