// Exercise Git's effective hook path in a disposable repository. Never stash,
// stage or commit the contributor's working tree merely to test hook dispatch.
import { spawnSync } from 'node:child_process';
import { mkdtemp, readFile, writeFile, mkdir, chmod, rm } from 'node:fs/promises';
import { resolve, join, isAbsolute } from 'node:path';
import { tmpdir } from 'node:os';
import assert from 'node:assert/strict';

const root = process.cwd();
const run = (args, cwd = root) => spawnSync('git', args, { cwd, encoding:'utf8' });
const git = (args, cwd = root) => {
  const result = run(args, cwd);
  if (result.status !== 0) throw new Error(result.stderr || result.stdout);
  return result.stdout.trim();
};
const common = resolve(root, git(['rev-parse','--git-common-dir']));
const configured = run(['config','--get','core.hooksPath']).stdout.trim();
const fixture = await mkdtemp(join(tmpdir(), 'magpie-hooks-'));
try {
  git(['init','--quiet'], fixture);
  const hookDir = join(fixture,'.git/hooks');
  await mkdir(hookDir,{ recursive:true });
  for (const hook of ['pre-commit','pre-push']) {
    const content = await readFile(join(common,'hooks',hook),'utf8');
    assert.match(content, /generated by prek/);
    assert.match(content, new RegExp(`--hook-type=${hook}`));
    await writeFile(join(hookDir,hook),content); await chmod(join(hookDir,hook),0o755);
  }
  // A local hooksPath maps to the corresponding fixture directory. A global
  // dispatcher is used directly, with Git resolving our fixture's common dir.
  const effective = configured ? (isAbsolute(configured) ? configured : resolve(root,configured)) : join(common,'hooks');
  const fixturePath = effective === join(common,'hooks') ? hookDir : effective;
  git(['config','core.hooksPath',fixturePath],fixture);
  await writeFile(join(fixture,'.pre-commit-config.yaml'), `repos:
  - repo: local
    hooks:
      - id: dispatch-probe
        name: MAGPIE_HOOK_DISPATCH_PROBE
        entry: node -e "console.error('MAGPIE_HOOK_DISPATCH_PROBE');process.exit(73)"
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-commit, pre-push]
`);
  git(['add','.pre-commit-config.yaml'],fixture);
  git(['-c','core.hooksPath=/dev/null','-c','user.name=Hook fixture','-c','user.email=fixture@example.invalid','commit','--quiet','-m','Create disposable hook fixture'],fixture);
  const sha = git(['rev-parse','HEAD'],fixture), stdin = join(fixture,'push-input');
  await writeFile(stdin, `refs/heads/main ${sha} refs/heads/main ${'0'.repeat(40)}\n`);
  for (const hook of ['pre-commit','pre-push']) {
    const result = run(['hook','run', ...(hook === 'pre-push' ? ['--to-stdin='+stdin] : []), hook, ...(hook === 'pre-push' ? ['--','fixture','https://example.invalid/fixture'] : [])],fixture);
    assert.notEqual(result.status,0, `${hook}: Git failed to block the deliberately failing hook`);
    assert.match(result.stdout + result.stderr, /MAGPIE_HOOK_DISPATCH_PROBE/, `${hook}: configured hook path did not reach the repository's prek hook`);
    console.log(`${hook}: Git → ${fixturePath} → repository prek → rejecting probe: passed`);
  }
  console.log('Both installed hooks are active. No commit or push was made in the project.');
} finally { await rm(fixture,{ recursive:true, force:true }); }
